# Generated by Django 4.1.1 on 2023-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=255)),
                ('timezone_offset', models.IntegerField()),
                ('current_dt', models.BigIntegerField()),
                ('current_sunrise', models.BigIntegerField()),
                ('current_sunset', models.BigIntegerField()),
                ('current_temp', models.FloatField()),
                ('current_feels_like', models.FloatField()),
                ('current_pressure', models.IntegerField()),
                ('current_humidity', models.IntegerField()),
                ('current_dew_point', models.FloatField()),
                ('current_uvi', models.FloatField()),
                ('current_clouds', models.IntegerField()),
                ('current_visibility', models.IntegerField()),
                ('current_wind_speed', models.FloatField()),
                ('current_wind_deg', models.IntegerField()),
                ('current_wind_gust', models.FloatField(blank=True, null=True)),
                ('current_weather', models.JSONField()),
            ],
        ),
    ]
