# Generated by Django 4.1.1 on 2023-12-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weatherdata'),
        ('api', '0007_aqiref_aqi'),
    ]

    operations = [
    ]
